#cloud-config
package_update: true
packages:
  - curl
  - jq
  - ubuntu-security-guide
  - iptables-persistent
  - unattended-upgrades
  - update-notifier-common

write_files:
  - path: /etc/sysctl.d/99-ipforward.conf
    content: |
      net.ipv4.ip_forward=1

runcmd:
  # apply sysctl changes
  - sysctl -p /etc/sysctl.d/99-ipforward.conf

  # masquerade only tailscale traffic
  - EXT_IFACE=$(ip route | grep default | awk '{print $5}')
  - iptables -t nat -A POSTROUTING -o $EXT_IFACE -j MASQUERADE
  - netfilter-persistent save

  # Harden using CIS Level 1 profile
  - usg audit cis_level1_server --json > /root/usg_audit.json
  - usg apply cis_level1_server --non-interactive

  # enable unattended upgrades
  - dpkg-reconfigure -f noninteractive unattended-upgrades
  - systemctl enable unattended-upgrades
  - systemctl start unattended-upgrades

  # allow automatic reboot if required
  - echo "Unattended-Upgrade::Automatic-Reboot \"true\";" >> /etc/apt/apt.conf.d/50unattended-upgrades
  - echo "Unattended-Upgrade::Automatic-Reboot-Time \"02:00\";" >> /etc/apt/apt.conf.d/50unattended-upgrades
